# Generated by Django 5.1.6 on 2025-02-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maceioin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(choices=[('Contabilidade', 'Contabilidade'), ('Financeiro', 'Financeiro'), ('Atendimento', 'Atendimento'), ('Orçamento', 'Orçamento'), ('TI', 'TI')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
